language: php

php:
  - 5.5
  - 5.6
  - nightly

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --prefer-source --no-interaction --dev
  - touch ./database/database.sqlite
